# Theme Configuration
minimal_mistakes_skin: "mint" # A modern, visually appealing color theme

# Locale
locale: "en-US"
rtl: false # Set true if using RTL (Right-To-Left) languages

# Site Identity
title: "Sandra M. K. Tsemo"
subtitle: "Ph.D. Candidate | Mathematical Modeling & Marine Ecology"
description: "Modeling nutrient cycles and understanding ecosystem dynamics through mathematical approaches."
url: "https://sandrakt.github.io"
baseurl: "" # Use empty unless deploying in a subfolder
repository: "sandraKT/sandrakt.github.io"

# Social Media Links
social:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sandraKT"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/your-profile"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:sandra.tsemo@leibniz-zmt.de"

# SEO Settings
google_site_verification: "your-google-site-verification-key"
bing_site_verification: "your-bing-verification-key"
naver_site_verification: "your-naver-verification-key"
yandex_site_verification: "your-yandex-verification-key"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-XXXXXX-X" # Replace with your Google Analytics Tracking ID
    anonymize_ip: true

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Search Engine
search: true
search_full_content: false
search_provider: "lunr" # Use Lunr for fast client-side searching

# Disqus Integration
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

# Social Sharing
twitter:
  username: "@sandraKT"
facebook:
  username: "your-facebook-username"

# Default Content Settings
defaults:
  # Set the default layout for new pages
  - scope:
      path: ""
      type: posts
    values:
      layout: "single"
      read_time: true
      comments: true

# Search Configuration with Lunr Search
lunr:
  search_within_pages: true

# Content Exclusions
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - node_modules
  - package.json
  - package-lock.json
  - test
  - docs

# CSS and JavaScript Paths
sass:
  sass_dir: "_sass"
  style: compressed

# Social Links and SEO Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sandraKT"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/your-profile"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:sandra.tsemo@leibniz-zmt.de"

# Defaults
defaults:
  # Default for non-specific layouts
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
      share: true
      comments: true
